apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-service
  name: frontend-service
spec:
  ports:
  - name: 30080-5000
    port: 30080
    protocol: TCP
    targetPort: 5000
  selector:
    app: frontend-service
  type: NodePort
status:
  loadBalancer: {}
