apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: frontend
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: frontend
    repoURL: 'https://github.com/szymonov3/ArgoCD'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

